export const actionTypes = {
  CHANGE_INPUT_SEARCH: "CHANGE_INPUT_SEARCH",
  SEARCH_STUDENT: "SEARCH_STUDENT",
  MOVE_TO_NEXTPAGE: "MOVE_TO_NEXTPAGE",
  MOVE_TO_PREVIOUSPAGE: "MOVE_TO_PREVIOUSPAGE",
  MOVE_EXACTLY_TO_PAGE: "MOVE_EXACTLY_TO_PAGE",
  CHANGE_PAGENUMBERS: "CHANGE_PAGENUMBERS",

  MODIFY_STUDENT: {
    EDITING_ID: "EDITING_ID",
    EDITING_IMG: "EDITING_IMG",
    EDITING_NAME: "EDITING_NAME",
    EDITING_PHONENUMBER: "EDITING_PHONENUMBER",
    EDITING_BIRTHDAY: "EDITING_BIRTHDAY",
    EDITING_DAYADMISSION: "EDITING_DAYADMISSION",
    EDITING_GENDER: "EDITING_GENDER",
    SAVE_EDIT: "SAVE_EDIT",
  },
  ADD_STUDENT: {
    ADDING_IMG: "ADDING_IMG",
    ADDING_NAME: "ADDING_NAME",
    ADDING_PHONENUMBER: "ADDING_PHONENUMBER",
    ADDING_BIRTHDAY: "ADDING_BIRTHDAY",
    ADDING_DAYADMISSION: "ADDING_DAYADMISSION",
    ADDING_GENDER: "ADDING_GENDER",
    CREATING_ID: "CREATING_ID",
    SAVE_ADD: "SAVE_ADD ",
  },
};
